from __future__ import annotations

from typing import Any, Protocol


class CachePort(Protocol):
    async def get(self, key: str) -> Any | None: ...

    async def set(self, key: str, value: Any, ttl_seconds: int) -> None: ...

    async def delete(self, key: str) -> None: ...

    async def increment_version(self, namespace: str) -> int: ...

    async def get_version(self, namespace: str) -> int: ...
